# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-25 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_name', models.CharField(max_length=100)),
                ('frames', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Frames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('video_path', models.FileField(max_length=1000, upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='frames',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deepseek.Videos'),
        ),
    ]
