# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-25 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepseek', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frames',
            new_name='Frame',
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
