# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-25 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepseek', '0002_auto_20170325_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_finish_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='process_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
