# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 14:16
from __future__ import unicode_literals

import deepseek.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepseek', '0004_auto_20170325_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.FileField(upload_to='temp'),
        ),
    ]
