# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-01 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepseek', '0005_auto_20170330_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='frame_path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
